{{- if .Values.ingress.webui.enabled -}}
{{- $fullName := include "sensu-go-helm.fullname" . -}}
{{- $ingressPath := .Values.ingress.webui.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-webui
  labels:
    app: {{ template "sensu-go-helm.name" . }}
    chart: {{ template "sensu-go-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.webui.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.webui.tls }}
  tls:
  {{- range .Values.ingress.webui.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.webui.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: "{{ $fullName }}-webui"
              servicePort: 3000
  {{- end }}
{{- end }}
