{{- if .Values.ingress.api.enabled -}}
{{- $fullName := include "sensu-go-helm.fullname" . -}}
{{- $ingressPath := .Values.ingress.api.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-api
  labels:
    app: {{ template "sensu-go-helm.name" . }}
    chart: {{ template "sensu-go-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.api.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.api.tls }}
  tls:
  {{- range .Values.ingress.api.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.api.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: "{{ $fullName }}-api"
              servicePort: 8080
  {{- end }}
{{- end }}
