apiVersion: v1
kind: Service
metadata:
  name: {{ template "sensu-go-helm.fullname" . }}-api
  labels:
    app: {{ template "sensu-go-helm.name" . }}
    chart: {{ template "sensu-go-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 8080
      protocol: TCP
      name: api
  selector:
    app: {{ template "sensu-go-helm.name" . }}
    release: {{ .Release.Name }}
